### ISSUE TITLE
ImSDK.jslib SyntaxError: Unexpected identifier,

### ISSUE THREAD

**Issue by jucel123456789** [TencentCloud/chat-sdk-unity#2]
can't build in webgl platform
![error wbgl](https://github.com/TencentCloud/chat-sdk-unity/assets/155602503/24701eac-9597-4ebb-8db6-ca3dcc00f432)

Build Error:
Library\Bee\artifacts\WebGL\build\debug_WebGL_wasm\build.js: failure to execute js library "D:\UNITY PROJECT\My Project\Library\PackageCache\com.tencent.imsdk.unity@5566ada2f9\Plugins\ImSDK.jslib": SyntaxError: Unexpected identifier,
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

**Comment by hexingcheng** [comment]
Version 1.9.3 resolves this bug. please upgrade.
